### ISSUE TITLE
一条小建议

### ISSUE THREAD

**Issue by huangzhicong3** [PointsCoder/Awesome-3D-Object-Detection-for-Autonomous-Driving#1]
你好，这是一篇很棒的文章。在3.2.2 小节中，我发现一处可能是笔误，从上下文看，感觉改成anchor-free更合理。

![image](https://user-images.githubusercontent.com/42371677/176397653-bb4a56fd-8b37-4ae0-9df3-a07c65438307.png)

**Comment by PointsCoder** [comment]
@huangzhicong3 已改，新版本晚些更新

Typo fixed. The new version will be updated later.
